TS0601 Dimmer gpp
zigpy/zha-device-handlers pull request #1122
Opened 2021-11-02 10:16 UTC by MattWestb

Adding GPP cluster and device "_TZE200_3p5ydos3".
Is getting status from the device but cant controlling it from ZHA.

Making is as draft so user can using it if they like but dont like merging in ZHA until it have more core function working.

Fixes #1103

2022-01-11 20:11 UTC, Tropaion commented
@MattWestb Are you still working on this? Is there any progress?
I bought this and didn't know it isn't supported currently.

2022-01-11 21:50 UTC, MattWestb commented
Not my but one very good user is working on tuya Dp dimmers and is reworking large things for getting it working OK https://github.com/zigpy/zha-device-handlers/pull/1247.
If you like try it out the work is don (not all os working but the ground is ther) look in https://github.com/zigpy/zha-device-handlers/issues/1033.

I was only making this for getting the first gang working for user that liking getting some function but is never going in and i deleting it the the new quirk is working and is being merged.

2022-01-11 23:37 UTC, Tropaion commented
@MattWestb Thanks^^ I dont understand it completely because I'm pretty new in this field, but when will this be available/how long does it take that it gets to ZHA?

2022-01-22 20:10 UTC, javicalle requested changes

2022-01-22 20:10 UTC, javicalle commented on zhaquirks/tuya/ts0601_dimmer.py
> +        # <SimpleDescriptor endpoint=1 profile=260 device_type=51 device_version=1 input_clusters=[0, 4, 5, 61184] output_clusters=[10, 25]>
The descriptor is not correct. I think it is better to remove it.

2022-01-23 19:40 UTC, MattWestb commented
Thanks for comments @javicalle but i cant testing the device and the original user was not interested so i was "leaving it as WIP" for user can downloading it and getting the first gang working.
I think its better you is integrating this device in your work and can testing it with interested users.

Mvh  Mattias

2022-01-25 17:18 UTC, MattWestb commented
Use the linked issues for implanting new devices with the new approach linked abow.

2022-01-25 17:18 UTC, closed without merging