Add support for Tuya DDS238-2 Din PowerMeter
zigpy/zha-device-handlers pull request #1155
Opened 2021-11-14 19:13 UTC by darckly

This is a Hiking DDS238-2 65A DIN Power Meter device, which supports measuring voltage, current, power, and counting total energy. The device also has a switch but seems the issue is present in device firmware, and the device sends the "ON" state even the device is switched off. 
![image](https://user-images.githubusercontent.com/49753351/141695079-243cf8c5-7a92-432e-9c24-d88343548dee.png)

2021-11-15 14:34 UTC, dmulcahey requested changes

2021-11-15 14:34 UTC, dmulcahey commented on zhaquirks/tuya/ts0601_din_power.py
> +            self.endpoint.device.energy_bus.listener_event(
you can remove the `Bus` and you can get the electrical measurement cluster to do the updates like this: 

https://github.com/zigpy/zha-device-handlers/blob/10dbcc4d64fdf748989e6d72ea169bc7163eb6ad/zhaquirks/xiaomi/aqara/tvoc.py#L31

the ep_attribute to access is: `electrical_measurement`

https://github.com/zigpy/zigpy/blob/7c168c1c2ca2a338676e5956d2277af7c40971d6/zigpy/zcl/clusters/homeautomation.py#L82

I would remove the `Bus` and do this for all of the attrs.

2021-11-15 14:34 UTC, dmulcahey commented on zhaquirks/tuya/ts0601_din_power.py
> +        self.endpoint.device.energy_bus.add_listener(self)
Do the same thing for the Metering cluster. Remove the `Bus` and update the values as outlined above.

2021-11-17 17:21 UTC, darckly commented
Updated, I use the standard switch_bus for TuyaOnOff.
Don't know is possible to remove it also.

2021-11-19 20:01 UTC, merged