Update ts0601 add new class
zigpy/zha-device-handlers pull request #1601
Opened 2022-06-04 00:39 UTC by caslubas

Add new class TuyaTripleSwitch_GP and add new device _TZE200_2hf7x9n3 
Reported in #1597

2022-06-04 07:07 UTC, javicalle commented
Add the `GreenPowerProxy` like in
https://github.com/zigpy/zha-device-handlers/issues/1597#issuecomment-1146210843

2022-06-04 07:09 UTC, javicalle requested changes

2022-06-04 07:09 UTC, javicalle commented on zhaquirks/tuya/ts0601_switch.py
> +## Reported in #1597
Remove one `#`

2022-06-04 21:11 UTC, javicalle requested changes
Add the GreenPowerProxy import like in
https://github.com/zigpy/zha-device-handlers/issues/1597#issuecomment-1146210843

2022-06-04 23:18 UTC, javicalle requested changes
Just the requested changes.

2022-06-04 23:18 UTC, javicalle commented on zhaquirks/tuya/ts0601_switch.py
> +from zigpy.zcl.clusters.general import Basic, GreenPowerProxy,Groups, Ota, Scenes, Time
Add a whitespace:
```
GreenPowerProxy, Groups
```

2022-06-04 23:18 UTC, javicalle commented on zhaquirks/tuya/ts0601_switch.py
> +from zhaquirks.tuya.mcu import MoesSwitchManufCluster, TuyaOnOff, TuyaOnOffManufCluster
Remove this line (already exists)

2022-06-05 10:28 UTC, javicalle commented
I'm sorry that this is giving you more trouble than expected.
I don't know if you know that in the 'Files changed' tab you can see the changes you are introducing in your PR:
* https://github.com/zigpy/zha-device-handlers/pull/1601/files

The latest changes have removed an existing class, which is not the point of your PR.

Since it was also necessary to add the 2 switch device definition, I have taken the liberty of creating a new PR (#1604) with the definitions for the 1 to 4 switch devices. I hope you don't mind.

If it is fine to you, please, close this PR and let's continous with the new one.

2022-06-07 02:55 UTC, caslubas commented
> If it is fine to you, please, close this PR and let's continous with the new one.

No problem for me, I'm still learning how to work with github.

2022-06-07 02:55 UTC, closed without merging