Add support for Tuya Switch TZ3000_18ejxno0
zigpy/zha-device-handlers pull request #1756
Opened 2022-09-15 12:09 UTC by dyatlov

A proper support for Tuya 2G Zigbee Switch `TZ3000_18ejxno0`.
The brand of the switch is `Moes`.
Interestengly, when attempting to use existing `MoesSwitchManufCluster` (which is used for TS0601 switches) it doesn't bind lights at all, so I used a generic `TuyaZBOnOffAttributeCluster` for the switch.
Another thing is that the switch by default came with `backlight_mode` set to `Light when On` (number `1`), which us useless.
After linking the switch I changed the backlight mode to `Light when Off` (number `2`) through modifying cluster attributes within `TuyaZBOnOffAttributeCluster` in Home Assistant UI.

2022-09-17 17:34 UTC, javicalle requested changes
Just some minor changes

2022-09-17 17:34 UTC, javicalle commented on zhaquirks/tuya/ts001x.py
> +                    Basic.cluster_id,
Just reorder with the 'numeric' one:
```python
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    TuyaZBE000Cluster.cluster_id,
                    TuyaZBExternalSwitchTypeCluster.cluster_id,
```

2022-09-17 17:34 UTC, javicalle commented on zhaquirks/tuya/ts001x.py
> +            # input_clusters=[3, 4, 5, 6, 57344, 57345, 0]
Same as below:
```python
# input_clusters=[0, 3, 4, 5, 6, 57344, 57345]
```

2022-09-17 17:34 UTC, javicalle commented on zhaquirks/tuya/ts001x.py
> +        MODELS_INFO: [("_TZ3000_18ejxno0", "TS0012")],
Let's try to leave only the model to see what happens...
```python
MODEL: "TS0012",
```

2022-09-17 17:34 UTC, javicalle commented on zhaquirks/tuya/ts001x.py
> +class Tuya_Double_No_N__TZ3000_18ejxno0(TuyaSwitch):
Don't reference the device in the class name.
Not sure which name can fit here. Maybe something like `Tuya_Double_No_N_Plus`?

2022-09-17 17:35 UTC, javicalle commented
The `MoesSwitchManufCluster` is used in Tuya devices with a MCU controller. Tipically all the devices that have a `TuyaManufacturerCluster` (0xef00). Not the case for these devices.

2022-09-17 17:39 UTC, javicalle commented
For those who are interested, the signature of this (2 gang) device is the same as `Tuya_Double_No_N` but without the cluster `TuyaZBE000Cluster` on endpoint 2.
What a garden delight Tuya has mounted 🌹 🌷 🍄 💮

2022-09-22 09:55 UTC, dyatlov commented
Thank you for the input @javicalle , I pushed the updated code to PR.

2022-09-22 09:58 UTC, javicalle approved these changes
LGTM

2022-09-22 10:01 UTC, javicalle commented
Failing tests not seems related to the PR.
@dmulcahey sorry to bother, test are failing with a `Failed to restore Python virtual environment from cache` error.

2022-09-26 12:46 UTC, merged