Add support for GiEX QT06 valve
zigpy/zha-device-handlers pull request #1937
Opened 2022-11-18 20:56 UTC by mbo18

Add support for GiEX QT06 valve

Fixes: https://github.com/zigpy/zha-device-handlers/issues/1622

2022-11-18 21:12 UTC, MattWestb commented
Use https://black.vercel.app/ copy and pace in the right and you is getting the fixed code in the left side.

2022-11-18 21:21 UTC, MattWestb commented
My record with black is over 10 time fixing for getting all right  ;-))

2022-11-18 21:23 UTC, mbo18 commented
> My record with black is over 10 time fixing for getting all right ;-))

Would have been 10+ without your link, thanks 👍

2022-11-19 01:00 UTC, javicalle requested changes
Just some gramatical changes to remove declaration overload.

2022-11-19 08:15 UTC, mbo18 commented on zhaquirks/tuya/ts0601_valve.py
> +GIEX_TUYA_VALVE_DURATION_ATTR = 0xEF72  # Last irrigation duration
You are right, change done

2022-11-19 08:16 UTC, mbo18 commented on zhaquirks/tuya/ts0601_valve.py
> +    """GiEX Tuya valve manufacturer cluster."""
Done

2022-11-19 08:16 UTC, mbo18 commented on zhaquirks/tuya/ts0601_valve.py
> +    """GiEX Tuya valve device."""
Done

2022-11-19 08:36 UTC, javicalle approved these changes
LGTM

2022-11-19 08:42 UTC, javicalle commented
BTW, Z2M is also listening (and dimissing) DP106. Do you have reports from it in your device?
`giexWaterValveCurrentTempurature: 106,`

2022-11-19 09:01 UTC, mbo18 commented
I did not test it as Z2M is dismissing it. Will do next week and open a new PR if needed

2022-11-19 10:03 UTC, javicalle commented
Sure, no problem. Just curious about what values is reporting (if none).

2022-11-19 14:19 UTC, merged

2022-11-20 21:34 UTC, mbo18 commented
> Sure, no problem. Just curious about what values is reporting (if none).

All I have is "None", so no value

2023-11-29 17:05 UTC, Copyrighter commented
any update guys? someone can complete support for this product?

https://zigbee.blakadder.com/GiEX_QT06.html
https://www.zigbee2mqtt.io/devices/QT06_1.html