Create ts0601_soil.py
zigpy/zha-device-handlers pull request #2102
Opened 2023-01-16 00:01 UTC by dgaust

ZHA Quirk to support the Tuya based Soil Moisture sensor. Based off the quirks ts0601_sensor.py and the zigbee-herdsman converter

https://github.com/zigpy/zha-device-handlers/issues/2093

Temperature value is multiplied by 100 to get degrees centigrade Humidty is based on the standard TuyaRelativeHumidity value Battery is multiplied by two to get battery % value

2023-01-16 19:29 UTC, javicalle commented
Thanks for your contribution and **good job** despite 'not 100% sure what I'm doing' 😉 

A few comments:

Edit your first post and put a `Fixes: #2093`. This way, issue will be closed once merged the PR.

I'm not sure if we need to create a new file for this devices. Until now is just another temp/hum sensor.
I would suggest to put the new code in the existing `ts0601_sensor.py`:
* `class SoilManufCluster(TuyaMCUCluster):`  <-- renamed from yours `TemperatureHumidityManufCluster`
* `class TuyaSoilSensor(CustomDevice):`

HA have specific definitions for 'moisture' entities. I will try to check if we can follow the implementations.

It seems that device is reporting also the temp UOM (probably also allows to set it). That would be a improvement, but can go in another PR.

2023-01-16 20:03 UTC, javicalle commented
It seems that most of the ZHA magic is already implemented. I would suggest to implement the device like:
* create a new `TuyaSoilCluster`
```python
class TuyaSoilMoisture(SoilMoisture, TuyaLocalCluster):
    """Tuya local SoilMoisture cluster."""

```

You will need to import the `SoilMoisture` class:
```python
from zigpy.zcl.clusters.measurement import (
    RelativeHumidity,
    SoilMoisture,
    TemperatureMeasurement,
)
```

* use the new class in your device (`dp_to_attribute` and `replacement`)

I believe that HA will create the new entity. And probably will be pretty similar to the old one but IMHO 'this is the way'.

2023-01-16 21:52 UTC, dgaust commented
> I was thinking about the same, but keep merged for now. Let's see how it grows first.

Ok, I've made those changes to the file, bringing the standalone file back into the sensor.py version. Have also added the soil moisture class rather than using humidity. It did create a new sensor in Home Assistant and all seems to be working fine

![image](https://user-images.githubusercontent.com/3413862/212771043-e7c43821-c392-470d-903b-44f7a19580b6.png)

2023-01-16 21:56 UTC, javicalle commented
You have the imports duplicated. Keep the 'new' format.

The temp OUM will not be an easy fix (ZHA assumes that temp units will be Celsius always). I believe that we can go 'as is'.

2023-01-16 22:01 UTC, dgaust commented
> You have the imports duplicated. Keep the 'new' format.
> 
> The temp OUM will not be an easy fix (ZHA assumes that temp units will be Celsius always). I believe that we can go 'as is'.

Yep, I'd noticed that once it failed and have made the adjustments.

2023-01-16 23:17 UTC, javicalle commented
You can check the isort report for more info:
https://github.com/zigpy/zha-device-handlers/actions/runs/3934353893/jobs/6729028066

The check complains about the extra break lines (the `-` lines). Delete it.

2023-01-16 23:38 UTC, dgaust commented
> You can check the isort report for more info: https://github.com/zigpy/zha-device-handlers/actions/runs/3934353893/jobs/6729028066
> 
> The check complains about the extra break lines (the `-` lines). Delete it.

Thansk, I didn't know how to interpret what the issue was :D

All fixed and tests passed.

2023-01-18 07:44 UTC, javicalle requested changes
A little fix to remove the `update_attribute` method.
If needed in a future we can go back to it.

2023-01-18 07:44 UTC, javicalle commented on zhaquirks/tuya/ts0601_sensor.py
> +
Remove the `update_attribute` method here. The `RH_MULTIPLIER` sates for RelativeHumidity. Keep just the class definition like:
```python
class TuyaSoilMoisture(SoilMoisture, TuyaLocalCluster):
    """Tuya local SoilMoisture cluster."""


```
(2 break lines before next class `TuyaRelativeHumidity`)

2023-01-18 07:44 UTC, javicalle commented on zhaquirks/tuya/ts0601_sensor.py
> +            dp_type=TuyaDPType.VALUE,
If removed from method, we need to add here the value conversion like:
```python
            dp_type=TuyaDPType.VALUE,
            converter=lambda x: x * 100,
```

2023-01-18 07:46 UTC, javicalle commented
With the last changes the PR will be fine to me.
But can you check yhe device logs for any warning about unsupported handlers or similar. There must be a DP=9 for the UOM

2023-01-18 18:17 UTC, javicalle approved these changes
LGTM

2023-01-23 12:14 UTC, merged