Add _TZ3000_qeuvnohg Tongou TO-Q-SY1-JZT
zigpy/zha-device-handlers pull request #2252
Opened 2023-03-05 10:04 UTC by arsenyspb

Original [issue/2005](https://github.com/zigpy/zha-device-handlers/issues/2005) and [pull/2008](https://github.com/zigpy/zha-device-handlers/pull/2008). I'm not able to push to @zleba 's [zleba:tuyaCircuitBreaker](https://github.com/zleba/zha-device-handlers/tree/tuyaCircuitBreaker) as not a maintaner, therefore this PR.

Following @javicalle 's hint [here](https://github.com/zigpy/zha-device-handlers/issues/1764#issuecomment-1272390644), and once quirk is installed this problem are gone [(tested)](https://www.evernote.com/shard/s151/sh/9f06b277-d45f-4ff7-b4d3-d8d1287208b5/IXMgWdpsTeE8GjaIfgHdQwklEFCfUQhEXuyYIDv3WLzsrfltSovN_uYm0Q) through `DIVISOR` and `MULTIPLIER` in `tuya/__init__.py`.

2023-03-05 10:19 UTC, javicalle requested changes
Checks fixes

2023-03-05 10:19 UTC, javicalle commented on zhaquirks/tuya/ts011f_plug.py
> +class Plug_CB_Metering(EnchantedDevice):
Add 2 blank lines before the class declaration. Like this:
```python
                OUTPUT_CLUSTERS: [],
            },
        },
    }


class Plug_CB_Metering(EnchantedDevice):
    """Circuit breaker with monitoring, e.g. Tongou TO-Q-SY1-JZT. First one using this definition was _TZ3000_qeuvnohg."""

    signature = {
        MODEL: "TS011F",
```

2023-03-05 10:19 UTC, javicalle commented on zhaquirks/tuya/ts011f_plug.py
> +                    TemperatureMeasurement.cluster_id, # Note: no temperature sensor claimed in manual and it's constant -6.3C
As states, 2 white spaces before the comment. Like this:
```python
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    TemperatureMeasurement.cluster_id,  # Note: no temperature sensor claimed in manual and it's constant -6.3C
                    Metering.cluster_id,
                    ElectricalMeasurement.cluster_id,
                    TuyaZBE000Cluster.cluster_id,
                    TuyaZBExternalSwitchTypeCluster.cluster_id,
                ],
```

2023-03-05 10:23 UTC, javicalle approved these changes
LGTM

2023-03-05 10:30 UTC, arsenyspb commented
@javicalle 🙏  kudos, you folks maintain the project really well, - I was able to learn everything I needed in a matter of hours (...or maybe it's just a productive Sunday).

How often you merge (...looks like to dev), what to RTFM about your release?

Basically, - when to remove my local quirk from `/config/custom_zha_quirks`

2023-03-05 10:51 UTC, javicalle commented
Sorry I'm just a collaborator. I'm not in charge to merge or release versions.
Usually before a new release most of the small PRs are merged, but there is no ETA for the versions.

2023-03-05 11:02 UTC, arsenyspb commented
Cool will keep an eye on this one and will remove based on release notes from upstream.

2023-03-06 22:17 UTC, zleba commented
Hi @arsenyspb, actually the measurement of the power (W), power consumption (kWh) and current (A) works well for me after using the quirk in the PR.
But I haven't managed to get the "Power factor" working (cos th).
If this entry is not required, you can go ahead.
It can be calculated as:
power / (current * voltage)
To my knowledge, there is no chance to know if the connected device is more like a capacitor or inductor...

2023-03-07 00:39 UTC, TheJulianJES commented on zhaquirks/tuya/ts011f_plug.py
> +class Plug_CB_Metering(EnchantedDevice):
just a note: Class names are normally `CamelCase` in Python and don't include underscores, but I see that underscores are used everywhere here, so let's keep it like this (until changed completely?)

2023-03-07 00:40 UTC, TheJulianJES approved these changes
LGTM. Thanks @arsenyspb and @zleba

2023-03-07 00:44 UTC, merged

2023-03-07 00:45 UTC, TheJulianJES commented
Changes will likely land in Home Assistant 2023.4.0 (hopefully even during the beta period).
Normally, library bumps only make it into "hotfix" releases if somewhat critical issues are fixed.

(See https://developers.home-assistant.io/ "Upcoming Events" for the HA Core release schedule)

> But I haven't managed to get the "Power factor" working (cos th).
If this entry is not required, you can go ahead.
To my knowledge, there is no chance to know if the connected device is more like a capacitor or inductor...

Yeah, ZHA (HA Core) shouldn't create the power factor entity if it's not supported. Just disable it for now.