Tuya Smoke detector TS0205 PST-YG500A
zigpy/zha-device-handlers pull request #2991
Opened 2024-02-19 10:25 UTC by cdalexndr

## Proposed change

![image](https://github.com/zigpy/zha-device-handlers/assets/22418250/f097a185-2904-48f8-88e5-02774ccc55cc)

## Additional information

## Checklist

- [x] The changes are tested and work correctly
- x ] `pre-commit` checks pass / the code has been formatted using Black
- [x] Tests have been added to verify that the new code works

2024-02-26 19:05 UTC, TheJulianJES requested changes
Thanks for the PR! I've added some suggestions.
Ideally, we should also add a test for the actual code (that translates the Tuya attribute to the `IasZone` attribute).

This test can mostly be copied IMO: https://github.com/zigpy/zha-device-handlers/blob/e4d0663aa4fb2f4bd0b41825f1942e3d29893375/tests/test_xiaomi.py#L781-L809

The opple cluster stuff just needs to be changed to the Tuya stuff (and the quirk path needs to be changed).
If you need help with adding this test, let me know and I'll add it, as soon as I have some time.

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +                self.endpoint.device.ias_bus.listener_event(
Docs still need to be updated, but we can call `update_attribute` on another cluster like this:
`self.endpoint.ias_zone.update_attribute(IasZone.AttributeDefs.zone_status.id, value)`

Please use that and remove all `Bus` usage

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +        super()._update_attribute(ZONE_STATUS, value)
This can be removed completely then if the suggestions from the above comment are implemented.

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +    _CONSTANT_ATTRIBUTES = {ZONE_TYPE: IasZone.ZoneType.Fire_Sensor}
Instead of the old `ZONE_TYPE` constant, let's use the new zigpy AttributeDefs: `IasZone.AttributeDefs.zone_type.id`

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +class TuyaIasZone(CustomCluster, IasZone):
I think we should use `LocalDataCluster` instead of `CustomCluster` here, since it's a "fake cluster".

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +        super().__init__(*args, **kwargs)
(This can also be removed then)

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +    # }
Let's remove this. It's in the test and IMO, it's enough if it's like also in the PR/issue description for this device.

2024-02-26 19:05 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +                    Basic.cluster_id,  # 0x0000
Can you also remove those cluster IDs comment at the end?
We're (mostly) not using them in quirks, so we should try to stay consistent.

2024-05-02 12:57 UTC, mr-bembel commented
Hello,

Are there any news to support the product in ZHA soon? I bought 4 of them...

2024-08-17 17:08 UTC, Fr33L4nc3r commented
@cdalexndr Seems the pipeline failed at pre-commit step. Since you fixed it in the past (https://github.com/zigpy/zha-device-handlers/pull/2991/commits/fa9848025ab0306627224b8b1adeb5617d9b7a37), any chance you could have a look again ?
It seems like there ain't much to have this PR approved (despite the change request still appearing in red, while it seemed addressed with https://github.com/zigpy/zha-device-handlers/pull/2991/commits/dcd03eb1035c7cd4ab2e283ba8c88b5b5464ff6b).

Looking forward to see this device recognized correctly and automatically in zha thanks to amazing community work like yours.

2024-08-26 19:52 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +    }
Can we use the new `AttributeDefs` style here? As an example, see:
https://github.com/zigpy/zha-device-handlers/blob/915ff9b41e7393e1f2eaa449bd6a09267fa84277/zhaquirks/legrand/cable_outlet.py#L51-L68

You can also remove `TUYA_SMOKE_DETECTED_ATTR` then and if it needs to be access anywhere else (except the attribute definition, where it should just be "hard-coded"), `TuyaSmokeDetectorCluster.AttributeDefs.smoke_detected.id` can be used.

2024-08-26 19:53 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +            )
Not sure if we really need this?

2024-08-27 17:55 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +            )
Removed it for now.

2024-08-27 17:56 UTC, TheJulianJES commented on zhaquirks/tuya/ts0205.py
> +    }
Changed.

2024-08-27 17:58 UTC, TheJulianJES approved these changes
Thanks, I think this should be fine.

2024-08-27 17:59 UTC, merged

2024-09-02 12:27 UTC, abmantis commented
@cdalexndr why is the `TuyaSmokeDetectorCluster` needed? The sensor worked fine previously, it would just show motion instead of smoke as the sensor type, but that is be fixed with just the addition of the `TuyaIasZone` cluster on line 57. So, why the extra `TuyaSmokeDetectorCluster` cluster?

2024-11-22 22:03 UTC, Fr33L4nc3r commented
Just received a Product Safety Recall mail from Aliexpress about this smoke detector, just sharing in case you didn't know, I know what I need to replace ASAP :/