Update ts000x.py
zigpy/zha-device-handlers pull request #2996
Opened 2024-02-22 11:47 UTC by Migsi

## Proposed change
Change device type of Switch_4G_GPP to be an actual switch, as the device consists of potential-free relais. Also the type switch is substitutable with other types using HA helpers, but not (or not easily) vice versa.

It would probably make sense to change this for other similar switches as well, but as I don't own any others, I don't want to change stuff blindy, potentially introducing unnecessary errors/misbehaviour.

I found no related tests to this device, so I didn't do anything in this regard as well, as I've got not enough time to read through your testframework (yet) :/

## Checklist
- [X] The changes are tested and work correctly
- [X] `pre-commit` checks pass / the code has been formatted using Black (are they run when using Github only?)
- [ ] Tests have been added to verify that the new code works

2024-02-26 18:44 UTC, TheJulianJES requested changes
The issue with this is that it'll break existing installations. Everyone who currently set it up will have the old entity become stale and get a new one.
We've avoided changing the device type for new quirks because of this.

Please see this section on how to change the device type locally:
https://www.home-assistant.io/integrations/zha/#modifying-the-device-type

2024-02-27 11:46 UTC, Migsi commented
> The issue with this is that it'll break existing installations. Everyone who currently set it up will have the old entity become stale and get a new one. We've avoided changing the device type for new quirks because of this.
> 
> Please see this section on how to change the device type locally: https://www.home-assistant.io/integrations/zha/#modifying-the-device-type

I see. So this PR becomes obsolete?

While it is possible to work around this, I still see it at least somewhat inconvenient for new users setting up this (and potentialy any other wrongly specified device). Wouldn't it be possible to ensure somehow the original device type continues working by automatically generating a proper helper, just as "switch device type" in the UI does? The latter only seems to work when the "base" entity was a generic switch, but not when it is something specific like e.g. a lamp in this case.

2024-03-03 15:36 UTC, Migsi commented
@TheJulianJES sorry for the ping, I'd just close the PR if it really became irrelevant.

2024-03-18 03:00 UTC, TheJulianJES commented
> Wouldn't it be possible to ensure somehow the original device type continues working by automatically generating a proper helper, just as "change device type" in the UI does? 

I know it's not ideal, but we can't really do this from quirks.

> The latter only seems to work when the "base" entity was a generic switch, but not when it is something specific like e.g. a lamp in this case.

That's a limitation on HA Core side, as the integration responsible for that is called "Switch as X" and only allows you to "convert" switches.

> So this PR becomes obsolete?

For now, probably yes. I'm aware the current situation isn't ideal (especially because you can't go from light to switch using HA UI and have to modify (ZHA) YAML configuration to fix this, but there's no "good" solution right now.)

2024-03-25 22:33 UTC, Migsi commented
> > Wouldn't it be possible to ensure somehow the original device type continues working by automatically generating a proper helper, just as "change device type" in the UI does?
> 
> I know it's not ideal, but we can't really do this from quirks.
>
> ...
> 
> > So this PR becomes obsolete?
> 
> For now, probably yes. I'm aware the current situation isn't ideal (especially because you can't go from light to switch using HA UI and have to modify (ZHA) YAML configuration to fix this, but there's no "good" solution right now.)

Bummer :( Hope this gets sorted at some point.

> > The latter only seems to work when the "base" entity was a generic switch, but not when it is something specific like e.g. a lamp in this case.
> 
> That's a limitation on HA Core side, as the integration responsible for that is called "Switch as X" and only allows you to "convert" switches.

I might have a look at that at some point. Trying to lift this restriction could mitigate this inconvenience at least a bit.

2024-09-28 23:16 UTC, closed without merging