Add model: _TZE204_dqolcpcp (x12 switch)
zigpy/zha-device-handlers pull request #3008
Opened 2024-02-27 09:32 UTC by hyosang82

## Proposed change

Add device model _TZE204_dqolcpcp (x12 switches)

## Additional information

## Checklist

- [x ] The changes are tested and work correctly
- [ x] `pre-commit` checks pass / the code has been formatted using Black
- [x ] Tests have been added to verify that the new code works

2024-02-28 00:17 UTC, javicalle commented
Not sure if that device implements it or if it make sense at all, but setting the `quirk_id` would enable a couple of configuration entities in HA (power on and backlight mode) :
```
quirk_id = TUYA_PLUG_MANUFACTURER
```

Have you checked it?

2024-02-28 00:24 UTC, javicalle requested changes

2024-02-28 00:24 UTC, javicalle commented on zhaquirks/tuya/ts0601_switch.py
> +            },
Remove extra whitespaces

2024-03-18 02:51 UTC, TheJulianJES commented on zhaquirks/tuya/ts0601_switch.py
> +            },
```suggestion
            },
```

2024-03-26 21:27 UTC, TheJulianJES approved these changes

2024-03-26 21:27 UTC, merged