Add Conecto TS0601 `_TZE200_zppcgbdj` temperature & humidity
zigpy/zha-device-handlers pull request #3026
Opened 2024-03-06 22:16 UTC by pianosaurus

The device is a rebranded Tuya temperature and humidity sensor, and the quirk is almost identical to one of the existing Tuya quirks (but with a different humidity multiplier). I am not sure if the device is also sold under other brand names, though I suppose that is quite likely. I figure it makes sense to put it in as a Tuya quirk.

## Proposed change

This pull request adds the quirk immediately after the most similar existing quirk. It is almost identical, though if follows the standard set by the rest of the file when it comes to humidity multiplier (commented line containing the default value of 100).

## Additional information

Fixes #3024 

I do not have the development environment available to run formatting or adding tests. Given that this is essentially a copy-paste of the quirk before it, and it works in manual testing, I hope that is OK.

## Checklist

- [x] The changes are tested and work correctly
- [ ] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

2024-03-14 09:16 UTC, javicalle requested changes

2024-03-14 09:16 UTC, javicalle commented on zhaquirks/tuya/ts0601_sensor.py
> +class TuyaTempHumiditySensor_Conecto_Display(CustomDevice):
Don't use brand names to quirks.
Maybe better `TuyaTempHumiditySensorVar02`?

2024-03-14 09:16 UTC, javicalle commented on zhaquirks/tuya/ts0601_sensor.py
> +    # RH_MULTIPLIER = 100
Remove comments

2024-03-14 09:16 UTC, javicalle commented on zhaquirks/tuya/ts0601_sensor.py
> +            ("_TZE200_zppcgbdj", "TS0601"),
You can add the brand here as a acomment:
```python
        MODELS_INFO: [
            ("_TZE200_zppcgbdj", "TS0601"),  # Conecto TH
```

2024-03-14 09:17 UTC, javicalle commented
The quirk is fine in general. Just some minor comments.

2024-03-17 23:20 UTC, pianosaurus commented
Agreed, and implemented as suggested.

2024-03-18 07:09 UTC, javicalle approved these changes
LGTM

2024-03-20 17:51 UTC, TheJulianJES approved these changes

2024-03-20 17:52 UTC, merged