Add support for a Tuya based single button switch: _TZ3000_ja5osu5g
zigpy/zha-device-handlers pull request #3153
Opened 2024-05-14 12:46 UTC by CRCinAU

Existing signature before quirk:
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4742, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0000",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0004",
        "0x0006",
        "0x1000",
        "0xe001"
      ],
      "output_clusters": [
        "0x0003",
        "0x0004",
        "0x0006",
        "0x0008",
        "0x000a",
        "0x0019",
        "0x1000"
      ]
    }
  },
  "manufacturer": "_TZ3000_ja5osu5g",
  "model": "TS004F",
  "class": "zigpy.device.Device"
}

Signature after quirk:
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4742, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0820",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0004",
        "0x1000",
        "0xe001"
      ],
      "output_clusters": [
        "0x0003",
        "0x0004",
        "0x0006",
        "0x0008",
        "0x000a",
        "0x0019",
        "0x0300",
        "0x1000"
      ]
    }
  },
  "manufacturer": "_TZ3000_ja5osu5g",
  "model": "TS004F",
  "class": "ts004f.TuyaSmartRemote004FSK_v2"
}

Tested in HA, and HA correctly receives button presses now:
![image](https://github.com/zigpy/zha-device-handlers/assets/3992884/15e4f9c9-cfed-44d1-8fed-b15328803e7c)

## Checklist

- [x] The changes are tested and work correctly
- [ ] `pre-commit` checks pass / the code has been formatted using Black
- [ ] Tests have been added to verify that the new code works

2024-05-14 19:59 UTC, MattWestb commented
Great you was getting it working and doing on PR !!!
Interesting is if the first version is working for the same "manufacturer" was working or if tuya have doing one new firmware version with the (crazy) change.

Naming of the class naming and reusing the old class DA is up to the maintainers but for me its looks OK !!

2024-05-14 20:04 UTC, MattWestb commented
PS: add in the first post for linking the issue:
Fixes https://github.com/zigpy/zha-device-handlers/issues/2212

2024-05-24 22:58 UTC, TheJulianJES requested changes
Thanks for the PR!
There are some minor changes that could be made to clean this up slightly.

2024-05-24 22:58 UTC, TheJulianJES commented on zhaquirks/tuya/ts004f.py
> +                DEVICE_TYPE: 0x0000,
Use `DeviceType.ON_OFF_SWITCH`

2024-05-24 22:58 UTC, TheJulianJES commented on zhaquirks/tuya/ts004f.py
> +    device_automation_triggers = {
These are the same triggers as the quirk above, right? 
Make the `_v2` class inherit from `TuyaSmartRemote004FSK` then and this whole `device_automation_triggers` section can be removed from the `_v2` class.

2024-05-24 22:58 UTC, TheJulianJES commented on zhaquirks/tuya/ts004f.py
> +class TuyaSmartRemote004FSK_v2(EnchantedDevice):
To make the _v2 class inherit from `TuyaSmartRemote004FSK`, change it to be like this:
```suggestion
class TuyaSmartRemote004FSK_v2(TuyaSmartRemote004FSK):
```

2024-05-24 22:58 UTC, TheJulianJES commented on zhaquirks/tuya/ts004f.py
> +    }
If the `replacement` is also exactly the same as the other class, this section can be removed if you make the `_v2 ` class inherit from the other class like I mentioned.

2024-05-25 02:26 UTC, CRCinAU commented
> Thanks for the PR! There are some minor changes that could be made to clean this up slightly.

Thanks - I had no idea exactly what I was doing with this, just what I managed to get working... I was hoping that someone with more of a clue could optimise it :)

I *think* I've done what you've asked properly - if you could please give it your eyeballs again and confirm.

2024-05-27 03:17 UTC, TheJulianJES approved these changes
Looks good to me. Thanks!

2024-05-28 00:05 UTC, merged

2024-06-04 15:25 UTC, AnalogThinker commented
Not sure if it's a quirk implementation issue, but the TS004F by _TZ3000_ja5osu5g (Single Button) seems to have issues interpreting data.
Behaviour : Button keeps switching back to "on" by itself after a while.

Although the commands are pretty straight forward for toggle, on and off:
```
[zigpy.zcl] [0xA502:1:0x0006] Decoded ZCL frame: OnOff:toggle()
[zigpy.zcl] [0xA502:1:0x0006] Received command 0x02 (TSN 90): toggle()

[zigpy.zcl] [0x5CAF:1:0x0006] Received ZCL frame: b'\x11\xcd\x01'
[zigpy.zcl] [0x5CAF:1:0x0006] Decoded ZCL frame: OnOff:on()
[zigpy.zcl] [0x5CAF:1:0x0006] Received command 0x01 (TSN 205): on()

[zigpy.zcl] [0xF0EA:1:0x0006] Received ZCL frame: b'\x11\x1f\x00'
[zigpy.zcl] [0xF0EA:1:0x0006] Decoded ZCL frame: OnOff:off()
[zigpy.zcl] [0xF0EA:1:0x0006] Received command 0x00 (TSN 31): off()
```

the switch would trigger back on by itself upon receiving this one (note Bool.true:1) with no user interaction:
```
[zigpy.zcl] [0x4D62:1:0x0006] Received ZCL frame: b'\x18!\n\x00\x00\x10\x01'
[zigpy.zcl] [0x4D62:1:0x0006] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x18>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=33, command_id=10, *direction=<Direction.Server_to_Client: 1>)
[zigpy.zcl] [0x4D62:1:0x0006] Decoded ZCL frame: OnOff:Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.true: 1>))])
[zigpy.zcl] [0x4D62:1:0x0006] Received command 0x0A (TSN 33): Report_Attributes(attribute_reports=[Attribute(attrid=0x0000, value=TypeValue(type=Bool, value=<Bool.true: 1>))])
[zigpy.zcl] [0x4D62:1:0x0006] Attribute report received: on_off=<Bool.true: 1>
```

2024-06-04 16:47 UTC, CRCinAU commented
> Not sure if it's a quirk implementation issue, but the TS004F by _TZ3000_ja5osu5g (Single Button) seems to have issues interpreting data. Behaviour : Button keeps switching back to "on" by itself after a while.
> 
> Although the commands are pretty straight forward for toggle, on and off:

If you hold the button down for ~3-4 seconds, it should change modes and work properly.

2024-06-04 17:15 UTC, MattWestb commented
@AnalogThinker Pleas post the diagnostic from the device card so can see with quirk (if) its using.

2024-06-04 17:29 UTC, AnalogThinker commented
Sure thing.
I have pulled 2 diags :
- The first one (ending in e81.json) is the default diag, indeed detected as ON_OFF_SWITCH, with the odd "StartUpBehaviour" feature that does not change the issue however it's set
- The second one (ending in 0df.json) is the diag after manually applying a quirk as the py code as suggested in issue 3108, which disabled the button entirely, although being connected.
- 
[zha-12430ffcfde958073c7ce7432ab1fb85-_TZ3000_ja5osu5g TS004F-435e26c054c689c5cb33ed9d52615e81.json](https://github.com/user-attachments/files/15568216/zha-12430ffcfde958073c7ce7432ab1fb85-_TZ3000_ja5osu5g.TS004F-435e26c054c689c5cb33ed9d52615e81.json)
[zha-12430ffcfde958073c7ce7432ab1fb85-_TZ3000_ja5osu5g TS004F-f11e5bfb65847fab16d313da482cb0df.json](https://github.com/user-attachments/files/15568217/zha-12430ffcfde958073c7ce7432ab1fb85-_TZ3000_ja5osu5g.TS004F-f11e5bfb65847fab16d313da482cb0df.json)

2024-06-04 17:54 UTC, MattWestb commented
The second one shall working "normal" then its have loading the the quirk for on switch.
The first one have: `"quirk_class": "zigpy.device.Device",` so light commands shall working but "tuya scene" commands not util you is getting on working quirk loaded for it.

2024-07-02 18:13 UTC, FerrumLogic commented
Please add also _TZ3000_egvb1p2g model, added model as mentioned in https://github.com/zigpy/zha-device-handlers/discussions/2212#discussioncomment-9431055 works great.

Existing signature before quirk:
`   "ieee": "**REDACTED**",
    "nwk": 7408,
    "manufacturer": "_TZ3000_egvb1p2g",
    "model": "TS004F",
    "name": "_TZ3000_egvb1p2g TS004F",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "quirk_id": null,
    "manufacturer_code": 4742,
    "power_source": "Battery or Unknown",
    "lqi": 120,
    "rssi": -70,
    "last_seen": "2024-07-02T20:26:23",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4742, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0000",
          "input_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0004",
            "0x0006",
            "0x1000",
            "0xe001"
          ],
          "output_clusters": [
            "0x0003",
            "0x0004",
            "0x0006",
            "0x0008",
            "0x000a",
            "0x0019",
            "0x1000"
          ]
        }
      },
      "manufacturer": "_TZ3000_egvb1p2g",
      "model": "TS004F"
    }`