Add Lonsonhome QS-Zigbee-C01
zigpy/zha-device-handlers pull request #875
Opened 2021-05-03 19:36 UTC by miit86

class QS-Zigbee-C01(CustomDevice):
    """Tuya smart curtain roller shutter."""

    signature = {
        # SizePrefixedSimpleDescriptor(endpoint=1, profile=260, device_type=0x0202, device_version=1, input_clusters=[0, 4, 5, 0x0102], output_clusters=[10, 25]))
        MODELS_INFO: [("_TZ3000_vd43bbfq", "TS130F")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    WindowCovering.cluster_id,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id,],
            },
        },
    }
    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaCoveringCluster,					
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id,Ota.cluster_id],
            },
        },
    }

2021-06-30 23:41 UTC, Adminiuga requested changes
Can you please address comments?

2021-06-30 23:41 UTC, Adminiuga commented on zhaquirks/tuya/ts130f.py
> +    attributes.update({0xF002: ("motor_reversal", t.enum8)})
```suggestion
    manufacturer_attributes = {
        0xF000: ("tuya_moving_state", t.enum8),
        0xF001: ("calibration", t.enum8),
        0xF002: ("motor_reversal", t.enum8),
    }
```

2021-06-30 23:41 UTC, Adminiuga commented on zhaquirks/tuya/ts130f.py
> +        if command_id == CMD_GO_TO_LIFT_PERCENTAGE:
Could you try this instead
```suggestion
    async def go_to_tilt_percentage(
        self, *args, manufacturer=None, expect_reply=True, tsn=None
    ):
        """Override default command to invert percent lift value."""
```

It is going to override just that command.

2021-10-03 20:42 UTC, closed without merging

2021-10-03 21:05 UTC, MattWestb commented
One question is your curtain roller shutter working with the updated quirk (is now using only MODEL and the endpoints cluster for loading so no need for MODELS_INFO for all devices) ?

2021-10-03 21:08 UTC, miit86 commented
Hi,
Yes it is working with the TS130F
I once started this request, but didn't know the steps/way to proceed.
I just closed the Request.

2021-10-03 21:11 UTC, MattWestb commented
Very good and as long tuya is doing all the same tuya way its working in ZHA :-))
And closing the PR then its not needed is good so its no need for it laying around :-)