Add handler for Philips LTD011 downlight
zigpy/zha-device-handlers pull request #919
Opened 2021-06-11 01:55 UTC by joshuaspence

This is mostly so that I can control the on-off behaviour for these lights.

2021-06-11 13:43 UTC, Adminiuga commented
Could you run black and isort on your changes

2021-06-16 05:33 UTC, joshuaspence commented
@Adminiuga Done

2021-06-16 13:42 UTC, joshuaspence commented
Hmm, not sure what happened as I used `pre-commit`. Will check tomorrow

2021-06-16 23:41 UTC, joshuaspence commented
Ok, builds should pass now. Sorry about that.

2021-06-30 23:20 UTC, Adminiuga requested changes
Overall looks good. Make the changes outlined in comments and it is good to go

2021-06-30 23:20 UTC, Adminiuga commented on zhaquirks/philips/ltd011.py
> +                    768,
this should be
```suggestion
                    Color.cluster_id,
```
but import it at top with `from zigpy.zcl.clusters.lighting import Color` see https://github.com/zigpy/zha-device-handlers/blob/66cdaf32eeb744f44453f5fca057c3c9ec42f2ac/zhaquirks/philips/zllextendedcolorlight.py#L14 for example

2021-06-30 23:20 UTC, Adminiuga commented on zhaquirks/philips/ltd011.py
> +                    4096,
this should be `LightLink.cluster_id`

2021-07-05 03:06 UTC, Adminiuga approved these changes

2021-07-05 03:06 UTC, merged